### ISSUE TITLE
Can't use in landscape mode.

### ISSUE THREAD

**Issue by Silvus10** [eleclab-rpi/5inch_480x854#1]
Hey, I recently got this, and started messing with the code to try to get it to be oriented landscape instead of portrait, and I am a little confused, as it seems to be freezing every time I try to start it with the parameters set to 

dislay_rotate=(1 or 3)
lcd_rotate=(1 or3) 

any advise?

**Comment by eleclab-rpi** [comment]
HI, you can set the display and touch screen to be horizontal as follows：

1. Add this line at the end of the file in the /boot/config.txt file
display_rotate=1  #1：90；2: 180； 3: 270

2. Select one of the following lines to add the touchscreen rotation function in the /etc/X11/xorg.conf.d/40-libinput-conf file after the MatchIsTouchscreen "on" line.

Select one of the following lines :
Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1”     #touchscreen rotate 90
Option “CalibrationMatrix” “-1 0 1 0 -1 1 0 0 1”   #touchscreen rotate 90
Option “CalibrationMatrix” “0 -1 1 1 0 0 0 0 1”    #touchscreen rotate 90

Modify 40-libinput-conf  as follows:
     Section "InputClass"
             Identifier "libinput touchscreen catchall"
             MatchIsTouchscreen "on"
             Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1” 

===================================================================  
If you don't have 40-libinput.conf this step 2, follow the 3 steps below, you may only need to operate step 3

1. sudo apt-get install xserver-xorg-input-libinput     
2. sudo mkdir /etc/X11/xorg.conf.d
3. sudo cp /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/



***@***.***
 
From: Silvus10
Date: 2022-03-31 00:39
To: eleclab-rpi/5inch_480x854
CC: Subscribed
Subject: [eleclab-rpi/5inch_480x854] Can't use in portrait mode. (Issue #1)
Hey, I recently got this, and started messing with the code to try to get it to be oriented portrait instead of vertically, and I am a little confused, as it seems to be freezing every time I try to start it with the parameters set to
dislay_rotate=(1 or 3)
lcd_rotate=(1 or3)
any advise?

**Comment by Silvus10** [comment]
performing the above with the recommended guidelines has caused my raspberry pi to lock into terminal only mode, which wouldn't be so bad, but i can't seem to modify /etc/X11/xorg.conf.d/40-libinput-conf from the terminal unlike using 
sudo nano /boot/config.txt, when i use 

sudo nano /etc/X11/xorg.conf.d/40-libinput-conf

I just get a blank file, no changes are optional.

might have to do a new flash to fix this. using the 

Display_rotate=1 

still causes the pi to freeze until it is powered off even with the 40-libinput-conf modified as specified.

**Comment by eleclab-rpi** [comment]
Well, that's the case with Linux, you need to have your mouse and keyboard ready at this point,
If you don't have 40-libinput.conf this step 2, follow the 3 steps below, you may only need to operate step 3

1. sudo apt-get install xserver-xorg-input-libinput
2. sudo mkdir /etc/X11/xorg.conf.d
3. sudo cp /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/ 


3. sudo cp /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/




***@***.***
 
From: Silvus10
Date: 2022-04-01 23:24
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
performing the above with the recommended guidelines has caused my raspberry pi to lock into terminal only mode, which wouldn't be so bad, but i can't seem to modify /etc/X11/xorg.conf.d/40-libinput-conf from the terminal unlike using
sudo nano /boot/config.txt, when i use
sudo nano /etc/X11/xorg.conf.d/40-libinput-conf
I just get a blank file, no changes are optional.
might have to do a new flash to fix this. using the
Display_rotate=1
still causes the pi to freeze until it is powered off even with the 40-libinput-conf modified as specified.

**Comment by Silvus10** [comment]
You know, that sort of talk isn't very contrsuctive. I'm not doing anything wrong, I'm literally following your instructions. And it's not working. And repeating the exact same thing a second time does not make the solution more clear. I have my keyboard and mouse, and I told you what I'm doing. What's with the hostility? I'm just trying to get my thing to work.

**Comment by eleclab-rpi** [comment]
Your email mentions an empty file:
-------------------------------------------------- ---------------------------------------
sudo nano /etc/X11/xorg.conf.d/40-libinput-conf

I just get a blank file, no changes are optional.
-------------------------------------------------- ---------------------------------------

Then this file is missing under /etc. To do step 3, copy this /usr/share/X11/xorg.conf.d/40-libinput.conf to /etc/X11/xorg.conf.d/ directory.

If you don't have 40-libinput.conf this step 2, follow the 3 steps below, you may only need to operate step 3

1. sudo apt-get install xserver-xorg-input-libinput
2. sudo mkdir /etc/X11/xorg.conf.d
3. sudo cp /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/



***@***.***
 
From: Silvus10
Date: 2022-04-02 11:25
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
You know, that sort of talk isn't very contrsuctive. I'm not doing anything wrong, I'm literally following your instructions. And it's not working. And repeating the exact same thing a second time does not make the solution more clear. I have my keyboard and mouse, and I told you what I'm doing. What's with the hostility? I'm just trying to get my thing to work.

**Comment by eleclab-rpi** [comment]
Hi, sorry, we often encounter various problems with linux, that's just a sigh.

A friend also encountered the situation that it was not displayed yesterday, it turned out that there was a problem with the download of the file on github. I emailed him config.txt and eleclab-dpi5inch.dtbo, and it worked normally.

How is your situation now?



***@***.***
 
From: Silvus10
Date: 2022-04-02 11:25
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
You know, that sort of talk isn't very contrsuctive. I'm not doing anything wrong, I'm literally following your instructions. And it's not working. And repeating the exact same thing a second time does not make the solution more clear. I have my keyboard and mouse, and I told you what I'm doing. What's with the hostility? I'm just trying to get my thing to work.

**Comment by Silvus10** [comment]
so i am in a position where i can make changes, but adding 

display_rotate=1

leaves me with a rainbow splash screen, followed by a black screen and nothing, that remains until i restart and remove the line manually by removing the line from the code. I don't know what is causing the issue on the file from github, but if i knew what was causing the conflict, i could resolve it, but it's hard to identify the issue when you can't see anything unfortunately. 

adding these lines (or any variation of each or combination of multiple): 

Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1”     #touchscreen rotate 90
Option “CalibrationMatrix” “-1 0 1 0 -1 1 0 0 1”   #touchscreen rotate 90
Option “CalibrationMatrix” “0 -1 1 1 0 0 0 0 1”    #touchscreen rotate 90

to /etc/X11/xorg.conf.d/40-libinput-conf file after the MatchIsTouchscreen "on" line. seems to disable the display function altogether.

**Comment by eleclab-rpi** [comment]
There is a rainbow when booting up, which is the fixed display of the Raspberry Pi, whether it is a DPI display, DSI, or HDMI, there will be.
I've turned the screen on now, and I'm synchronizing with you. Are you using RPI4? bullseye?



***@***.***
 
From: Silvus10
Date: 2022-04-02 14:00
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
so i am in a position where i can make changes, but adding
display_rotate=1
leaves me with a rainbow splash screen, followed by a black screen and nothing, that remains until i restart and remove the line manually by removing the line from the code. I don't know what is causing the issue on the file from github, but if i knew what was causing the conflict, i could resolve it, but it's hard to identify the issue when you can't see anything unfortunately.
adding these lines (or any variation of each or combination of multiple):
Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1” #touchscreen rotate 90
Option “CalibrationMatrix” “-1 0 1 0 -1 1 0 0 1” #touchscreen rotate 90
Option “CalibrationMatrix” “0 -1 1 1 0 0 0 0 1” #touchscreen rotate 90
to /etc/X11/xorg.conf.d/40-libinput-conf file after the MatchIsTouchscreen "on" line. seems to disable the display function altogether.

**Comment by Silvus10** [comment]
yes, raspberry pi bullseye, I am on a 4b specifically, it's a fresh install most of the time. I'm using the 64 bit version (not sure if that would make any real difference, but thought i would mention it just in case.)

**Comment by eleclab-rpi** [comment]
***@***.***
 
From: Silvus10
Date: 2022-04-02 14:26
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
yes, raspberry pi bullseye, I am on a 4b specifically, it's a fresh install most of the time. I'm using the 64 bit version (not sure if that would make any real difference, but thought i would mention it just in case.)

**Comment by eleclab-rpi** [comment]
***@***.***
 
From: Silvus10
Date: 2022-04-02 14:26
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
yes, raspberry pi bullseye, I am on a 4b specifically, it's a fresh install most of the time. I'm using the 64 bit version (not sure if that would make any real difference, but thought i would mention it just in case.)

**Comment by eleclab-rpi** [comment]
It's a pity that the RPI4 and arm64 bullseye cannot be rotated on it.
RPI4 will have this difference in actual use. In addition, there will be different results when HDMI timings are output. So far we have found 2 points of this.



***@***.***
 
From: Silvus10
Date: 2022-04-02 14:26
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
yes, raspberry pi bullseye, I am on a 4b specifically, it's a fresh install most of the time. I'm using the 64 bit version (not sure if that would make any real difference, but thought i would mention it just in case.)

**Comment by Silvus10** [comment]
I'm game to figure it out, i just need to understand how the parameters are interpreted and what needs to be changed, additionally, would i have different results if I used the 32 bit version? my primary goal is to get it consistently operating horizonally, so i don't mind a little muscle and elbowgrease.

**Comment by eleclab-rpi** [comment]
Is it RPI4+32bit bullseye? I  reburn a TF card to see



***@***.***
 
From: Silvus10
Date: 2022-04-02 15:11
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
I'm game to figure it out, i just need to understand how the parameters are interpreted and what needs to be changed, additionally, would i have different results if I used the 32 bit version? my primary goal is to get it consistently operating horizonally, so i don't mind a little muscle and elbowgrease.

**Comment by eleclab-rpi** [comment]
2022-01-28-raspios-bullseye-armhf + RPI4 is normal in 480x854 vertical mode.



***@***.***
 
From: ***@***.***
Date: 2022-04-02 16:09
To: eleclab-rpi/5inch_480x854; eleclab-rpi/5inch_480x854
CC: Comment
Subject: Re: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
I downloaded 2022-01-28-raspios-bullseye-armhf, and started it on RPI4, but the splash screen will tear and not enter the desktop, this problem has been shown on RPI BBS, but it has not been solved .


I plugged the bullseye into the RPI1 and it showed normal. Probably one of the different points of the RPI4 I mentioned.





***@***.***
 
From: Silvus10
Date: 2022-04-02 14:26
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
yes, raspberry pi bullseye, I am on a 4b specifically, it's a fresh install most of the time. I'm using the 64 bit version (not sure if that would make any real difference, but thought i would mention it just in case.)

**Comment by Silvus10** [comment]
using 32 bit didn't manage to change anything it seems, horizontal is still a hard no go, either, way, i'm gonna try tweaking the timing options and see if I can maybe get it to work. i think without messing with the 

sudo cp /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/

side of things seems to be the best approach, as messing with that whatsoever seems to brick VNC and the screen and wont go beyond text when changed in the needed way. I'll let you know if i find anything that works though! should be pretty cut and dry, since if i can get it working with just messing with the config, in theory, it should only require a little back and forth with the computer/pi.

**Comment by eleclab-rpi** [comment]
I sent 2 files to you to try, do you have RPI1~RPI3? Currently they are all working fine, try them if you have them available.

RPI4 is still not resolved yet, there should be differences in the LCD part of the CPU.

Is vertical 480x854 display normal now?



***@***.***
 
From: Silvus10
Date: 2022-04-05 06:13
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
using 32 bit didn't manage to change anything it seems, horizontal is still a hard no go, either, way, i'm gonna try tweaking the timing options and see if I can maybe get it to work. i think without messing with the
sudo cp /usr/share/X11/xorg.conf.d/40-libinput.conf /etc/X11/xorg.conf.d/
side of things seems to be the best approach, as messing with that whatsoever seems to brick VNC and the screen and wont go beyond text when changed in the needed way. I'll let you know if i find anything that works though! should be pretty cut and dry, since if i can get it working with just messing with the config, in theory, it should only require a little back and forth with the computer/pi.

**Comment by Silvus10** [comment]
> is vertical 480x854 display normal now? >

vertical never really had much of a problem, its specifically horizontal i am having issues with.

**Comment by eleclab-rpi** [comment]
PRI4+2022-01-28-raspios-bullseye-armhf   rotate 180 degrees is also fine (display_rotate=2  #1：90；2: 180； 3: 270).

When starting at 90 degrees and 270  , The color bar is normal at startup, but after that the black screen does not enter the desktop.

There is also no landscape setting in the Appearance settings.

like this link：
https://forums.raspberrypi.com/viewtopic.php?t=246146



***@***.***
 
From: Silvus10
Date: 2022-04-05 08:19
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
is vertical 480x854 display normal now? >
vertical never really had much of a problem, its specifically horizontal i am having issues with.

**Comment by Silvus10** [comment]
right, but my objective is to get it working in the 90 (or 270) position.  I'm gonna play around with the code and see if i can't get it to work horizontally, but that is my end objective. viewing angles are substantially more appealing, as things frequently don't fully fit on the screen, even direct downloading from github is a nuisance because it treats it like a mobile window under a certain size format.

**Comment by eleclab-rpi** [comment]
The current version of os has not solved this problem on RPI4, it can only be used on RPI1~RPI3.

I modified 480x854-->480x856 for a test, but the display is blurry and jittery, but the rotation can be done.

dpi_timings=480 0 60 2 55 856 0 16 2 22 0 0 0 60 0 32000000 6
dtoverlay=eleclab-dpi5inch
display_rotate=1  #1：90；2: 180； 3: 270   , Need to modify 40-libinput.conf



***@***.***
 
From: Silvus10
Date: 2022-04-05 08:54
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
right, but my objective is to get it working in the 90 (or 270) position. I'm gonna play around with the code and see if i can't get it to work horizontally, but that is my end objective. viewing angles are substantially more appealing, as things frequently don't fully fit on the screen, even direct downloading from github is a nuisance because it treats it like a mobile window under a certain size format.

**Comment by eleclab-rpi** [comment]
ok, it seems that I made the Xh2.54 socket of the screen bigger by using the RPI1 tinned pin headers, and the RPI4 plugged in a little bit of poor contact. Now they don't blur the screen or flicker the screen, and the RPI4 horizontal screen displays well.
How are you over there?



***@***.***
 
From: Silvus10
Date: 2022-04-05 08:54
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
right, but my objective is to get it working in the 90 (or 270) position. I'm gonna play around with the code and see if i can't get it to work horizontally, but that is my end objective. viewing angles are substantially more appealing, as things frequently don't fully fit on the screen, even direct downloading from github is a nuisance because it treats it like a mobile window under a certain size format.

**Comment by Silvus10** [comment]
alright, so after changing the LCD timing, i have visual success for horizontal! I'll have to tweak it to get the best outcome, but that did the trick, although, input seems to be way off, which doesn't effect my project since i am going to be using a keyboard and mouse to control the pi anyways, but i am happy with the results, seems smooth and clean, weird how a single digit can make such a huge difference! I'm gonna save a backup of this version of the code for future use! thanks for all the help!

**Comment by eleclab-rpi** [comment]
Very good! You are welcome. Thanks for your feedback.
Because the LCD part of PRI4 must have changed, otherwise the same TF card insertion will not have different effects, success is victory.
Happy using!



***@***.***
 
From: Silvus10
Date: 2022-04-05 11:42
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
alright, so after changing the LCD timing, i have visual success for horizontal! I'll have to tweak it to get the best outcome, but that did the trick, although, input seems to be way off, which doesn't effect my project since i am going to be using a keyboard and mouse to control the pi anyways, but i am happy with the results, seems smooth and clean, weird how a single digit can make such a huge difference! I'm gonna save a backup of this version of the code for future use! thanks for all the help!

**Comment by eleclab-rpi** [comment]
I downloaded 2022-01-28-raspios-bullseye-armhf, and started it on RPI4, but the splash screen will tear and not enter the desktop, this problem has been shown on RPI BBS, but it has not been solved .


I plugged the bullseye into the RPI1 and it showed normal. Probably one of the different points of the RPI4 I mentioned.





***@***.***
 
From: Silvus10
Date: 2022-04-02 14:26
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
yes, raspberry pi bullseye, I am on a 4b specifically, it's a fresh install most of the time. I'm using the 64 bit version (not sure if that would make any real difference, but thought i would mention it just in case.)

**Comment by eleclab-rpi** [comment]
Do you have RPI1~3? I remember that it seems that the rotation cannot be completed on RPI4, and it is normal to put the TF card on RPI1~3.



***@***.***
 
From: Silvus10
Date: 2022-04-02 14:00
To: eleclab-rpi/5inch_480x854
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/5inch_480x854] Can't use in landscape mode. (Issue #1)
so i am in a position where i can make changes, but adding
display_rotate=1
leaves me with a rainbow splash screen, followed by a black screen and nothing, that remains until i restart and remove the line manually by removing the line from the code. I don't know what is causing the issue on the file from github, but if i knew what was causing the conflict, i could resolve it, but it's hard to identify the issue when you can't see anything unfortunately.
adding these lines (or any variation of each or combination of multiple):
Option “CalibrationMatrix” “0 1 0 -1 0 1 0 0 1” #touchscreen rotate 90
Option “CalibrationMatrix” “-1 0 1 0 -1 1 0 0 1” #touchscreen rotate 90
Option “CalibrationMatrix” “0 -1 1 1 0 0 0 0 1” #touchscreen rotate 90
to /etc/X11/xorg.conf.d/40-libinput-conf file after the MatchIsTouchscreen "on" line. seems to disable the display function altogether.
